service: serverless-quotes-api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  environment:
    QUOTES_TABLE: ${self:service}-project-quotes
    TEMPLATES_TABLE: ${self:service}-templates-quotes
    SECTIONS_TABLE: ${self:service}-sections

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - src/**
    - test/**

functions:
  createProjectQuote:
    handler: dist/src/handlers/projectQuotes/createProjectQuote.handler
    timeout: 30
    events:
      - http:
          path: projects/{projectId}/quotes
          method: post
  updateProjectQuote:
    handler: dist/src/handlers/projectQuotes/updateProjectQuote.handler
    timeout: 30
    events:
      - http:
          path: projects/{projectId}/quotes/{quoteId}
          method: put
  getProjectQuote:
    handler: dist/src/handlers/projectQuotes/getProjectQuote.handler
    timeout: 30
    events:
      - http:
          path: projects/{projectId}/quotes/{quoteId}
          method: get
  deleteProjectQuote:
    handler: dist/src/handlers/projectQuotes/deleteProjectQuote.handler
    timeout: 30
    events:
      - http:
          path: projects/{projectId}/quotes/{quoteId}
          method: delete
  # Template Quotes
  createTemplateQuote:
    handler: dist/src/handlers/templateQuotes/createTemplateQuote.handler
    timeout: 30
    events:
      - http:
          path: templates/quotes
          method: post
  updateTemplateQuote:
    handler: dist/src/handlers/templateQuotes/updateTemplateQuote.handler
    timeout: 30
    events:
      - http:
          path: templates/quotes/{quoteId}
          method: put
  getTemplateQuote:
    handler: dist/src/handlers/templateQuotes/getTemplateQuote.handler
    timeout: 30
    events:
      - http:
          path: templates/quotes/{quoteId}
          method: get
  deleteTemplateQuote:
    handler: dist/src/handlers/templateQuotes/deleteTemplateQuote.handler
    timeout: 30
    events:
      - http:
          path: templates/quotes/{quoteId}
          method: delete


resources:
  Resources:
    # Quotes Table 
    QuotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.QUOTES_TABLE}
        AttributeDefinitions:
          - AttributeName: quoteId
            AttributeType: S
          - AttributeName: projectId
            AttributeType: S
        KeySchema:
          - AttributeName: quoteId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ProjectIndex
            KeySchema:
              - AttributeName: projectId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      

    TemplatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TEMPLATES_TABLE}
        AttributeDefinitions:
          - AttributeName: quoteId
            AttributeType: S
        KeySchema:
          - AttributeName: quoteId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


    SectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.SECTIONS_TABLE}
        AttributeDefinitions:
          - AttributeName: quoteId
            AttributeType: S
        KeySchema:
          - AttributeName: quoteId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      
